### ISSUE TITLE
RB-T: HF20: Determine which tutorials are broken

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal-tutorials-rb#27]
**AC**
- [x] In `# Results` list which tutorials are not working. Otherwise, report that all are working.

**Comment by inertia186** [comment]
# Result

So, I was going to get fancy and write a quick script to check each tutorial, but turns out some tutorials need arguments to execute, which isn't a full test, and some don't terminate (streaming).  So if we wanted something like that, it'd be better to have a small framework in place to deal with the actual tutorial commands, like we do with `curl` on the main devportal (maybe keyed on the `# To Run` section would work, including the `git clone` command for each tutorial).

Anyway, after both (somewhat) automated and manual inspection, all tutorials are working.  I also went through the tutorials to look for any typos in the setup instructions.

* We have old instructions that need to get an update.  This refers to ruby scripts in `devportal`, when we didn't have a dedicated github project: https://github.com/steemit/devportal-tutorials-rb/tree/master/tutorials/00_getting_started#examples
* The `README.md` of tutorial 12 has a jekyll that should be removed: https://github.com/steemit/devportal-tutorials-rb/tree/master/tutorials/12_edit_content_patching
